spring.application.name=Trial
spring.datasource.url=jdbc:mysql://localhost:3306/progress_db
spring.datasource.username=root
spring.datasource.password=Drogheda1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080
# Enable full debug mode to see hidden errors
debug=true
# Force web errors to show in the console
logging.level.org.springframework.web=DEBUG
# Show the exact SQL errors if the database is the problem
logging.level.org.hibernate.SQL=DEBUG
